//Pet.js
export const furry = [
  {
    name: "Luna",
    description: "A gentle and affectionate 2-year-old indie cat with striking blue eyes and a soft cream coat. Luna loves cozy naps on blankets and is seeking a loving forever home.",
    url: "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?cs=srgb&dl=pexels-pixabay-45201.jpg&fm=jpg",
    alt: "rescued female cat",
    age: "3 months",
    breed: "Indie",
  },
  {
    name: "Choco",
    description: "Meet Choco, a curious and playful 4-year-old tabby. Always ready to chase a toy or explore every corner, Choco will bring energy and joy to your family.",
    url: "https://images.unsplash.com/photo-1529778873920-4da4926a72c2?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y3V0ZSUyMGNhdHxlbnwwfHwwfHx8MA%3D%3D",
    alt: "rescued catto!",
     age: "2 months",
    breed: "Bengal",
  },
  {
    name: "Happy",
    description: "A brave, specially abled indie cat with a heart full of joy. Happy brings a smile wherever she goes and loves cuddles and chin scratches. Ready for a compassionate adopter.",
    url: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2F0c3xlbnwwfHwwfHx8MA%3D%3D",
    alt: "female cat",
    age: "1 year",
    breed: "Indie",
  },
  {
    name: "Brownie",
    description: "A sweet and friendly indie dog who is always eager to greet you with a wagging tail. Loves walks and gentle pats, Brownie is looking for a family to cherish him forever.",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKRSvO8x5LQjNJ_FQC347Tbh-Lt24TSv4sYQ&s",
    alt: "rescued indie",
    age: "8 months",
    breed: "Indie",
  },
  {
    name: "boba",
    description: "Boba is an adventurous indie puppy, full of playful energy and curiosity. Loves playing outside and exploring new places. Perfect for an active and loving home.",
    url: "https://pawstro.com//wp-content/uploads/2022/06/indiandog.jpg",
    alt: "rescued indie pup",
    age: "4 months",
    breed: "Indie",
  },
  {
    name: "Taffy",
    description: "Taffy is a lively indie pup who loves ball games in the park. Always ready for fun and is a loyal friend to their humans. Adopt Taffy for endless games and affection.",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuJPX9N7To_Frj_TcsY0GqpQwtGd1bU5UEag&s",
    alt: "rescued pup",
     age: "5 years",
    breed: "Indie",
  },
   {
    name: "conquerer",
     description: "An inspiring, specially abled tabby cat who moves with the help of her wheelchair. She enjoys the outdoors and embraces life’s adventures. Ready for someone with a big heart and gentle hands.",
    url: "https://www.catster.com/wp-content/uploads/2015/02/tabby-longhair-cat-standing-outdoors-in-the-garden-with-walking-aid-or-wheelchair_Nils-Jacobi_Shutterstock.jpg",
    alt: "rescued female cat",
     age: "3 years",
    breed: "Persian",
  },
  {
    name: "Beauty",
    description: "A stunning calico cat with a soft, plush coat and curious eyes. Gentle and loving, Beauty enjoys a quiet lap and a comfy bed. Will make a wonderful companion.",
    url: "https://blogs.columbian.com/cat-tales/wp-content/uploads/sites/43/2016/05/AdobeStock_99334770.jpeg",
    alt: "rescued catto!",
     age: "2 years",
    breed: "Calico",
  },
  {
    name: "Chalky",
    description: "Chalky is a specially abled, kind-hearted cat who adapts gracefully to challenges. Enjoys gentle interactions and long naps in warm spots. Perfect for a special adopter.",
    url: "https://www.thehomesteadanimalhospital.com/wp-content/uploads/2022/11/shutterstock_1298327710-1.jpg",
    alt: "female cat",
     age: "2 years",
    breed: "Indie",
  },
  {
    name: "Ola",
     description: "Ola is a rescued macaw loves chew toys and quality time with people. Enjoys sunbathing in the garden and making friends with other pets.",
    url: "https://images.squarespace-cdn.com/content/v1/559d822ae4b0b0ab59484d42/1444848971854-TXMYY9OHZIIKY9K54UF2/Adopt-Tika.jpg",
    alt: "rescued indie",
     age: "7 years",
    breed: "Blue Macaw",
  },
  {
    name: "Mango",
  description: "A charming, friendly white-bellied bird who loves playful flights and chirping. Enjoys companionship and is perfect for bird-loving families.",
    url: "https://companionparrots.org/wp-content/uploads/2024/05/Tweek-M-10-White-bellied-Caique-uai-1103x1103.jpg",
    alt: "rescued indie pup",
     age: "9 years",
    breed: "Conour",
  },
  {
    name: "Taffy",
    description: "Taffy is a playful beagle mix, always on the move and chasing after toys. Loves making new friends and is happiest during playtime in the sun.",    url: "https://i.natgeofe.com/n/548467d8-c5f1-4551-9f58-6817a8d2c45e/NationalGeographic_2572187_16x9.jpg?w=1200",
    alt: "rescued pup",
     age: "2 years",
    breed: "Beag;e",
  },
  {
    name: "Moony",
     description: "Moony is a soft-coated indie cat, gentle with children and fond of toys. Adorable, affectionate, and ready to brighten up any home.",
    url: "https://www.animalaidunlimited.org/wp-content/uploads/2023/04/Goli_Adoption_Animal_Aid_Unlimited-1-555x370.jpg",
    alt: "rescued catto!",
     age: "3 years",
    breed: "Indie",
  },
  {
    name: "Naughty & Happy",
    description: "This cheerful pair of specially abled cats are full of mischief and delight. Despite their challenges, they love life and will charm anyone they meet.",
    url: "https://www.koin.com/wp-content/uploads/sites/10/2021/10/Image-5.jpg",
    alt: "female cat",
     age: "2 years",
    breed: "Spitz",
  },
  {
    name: "Snowy",
   description: "Snowy is a gentle, friendly indie dog with a striking white coat. Loves cuddles during winter and is quick to make friends with everyone.",
    url: "https://media.istockphoto.com/id/1090606186/photo/white-adoptable-dog.jpg?s=612x612&w=0&k=20&c=vxpgJbttxSk0TsqNODI5X0MJ3pC4I96AUv5pm-XhV_g=",
    alt: "rescued indie",
     age: "5 years",
    breed: "Indie",
  },
  {
    name: "Greeny",
     description: "Greeny is a lively rescued parrot who adds color and music to your life. Enjoys perching and chirping in the sunshine—a wonderful friend for bird enthusiasts.",
    url: "https://ontariospca.ca/wp-content/uploads/2019/01/Bird-care-768x512.jpg",
    alt: "rescued indie pup",
     age: "7 years",
    breed: "Indie",
  },
];
